name: Build & Publish Docker image

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: enoflag/ctfd
        tags: latest
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
