# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ enotraining ]
  pull_request:
    branches: [ enotraining ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8/black
      run: |
        pip install flake8 black
        flake8 --ignore=E402,E501,E712,W503,E203,I002 --exclude=CTFd/uploads CTFd/ migrations/ tests/
        black --check --exclude=CTFd/uploads --exclude=node_modules .
    - name: Test with pytest
      run: |
        pip install pytest coverage pytest-cov moto bandit mock freezegun
        pytest --cov=CTFd --cov-context=test --ignore=node_modules/ --disable-warnings
        bandit -r CTFd -x CTFd/uploads
